global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "promtail"
    static_configs:
      - targets: ["localhost:9080"]

  - job_name: "loki"
    static_configs:
      - targets: ["localhost:3100"]
